---
- name: Add Jenkins apt key
  apt_key: url=http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key state=present

- name: Add Jenkins repository to sources
  apt_repository: repo="deb http://pkg.jenkins-ci.org/debian-stable binary/" state=present

- name: Update APT package cache
  apt: update_cache=yes

- name: Install Jenkins
  apt: name=jenkins state=latest install_recommends=yes

- name: Ensure Jenkins is started and runs on startup
  service: name=jenkins state=started enabled=yes

- name: Wait for Jenkins to start up before proceeding next step
  shell: "curl -D - --silent http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: 60
  delay: 5
  changed_when: false
